### PR TITLE
Expose data dir

### PR DESCRIPTION
**Pull request by idky137**
Exposes validator data_dir to make it settable in user code.

Where necessary Tempdir has been replaced with PathBuf.

### CODE REVIEW

**Comment by Oscar-Pepper** [comment]
> Exposes validator data_dir to make it settable in user code.
> 
> Where necessary Tempdir has been replaced with PathBuf.

the issue with this approach is `into_path` turns the TempDir into a permanent directory. I got around this in two ways:
1. for regtest, the chain cache is copied into the temporary data dir from a specifed permanent location
2. for testnet/mainnet, the pathbuf to the chain cache is set to a specified permanent directory

I imagine for your purposes you could do a similar thing as 2 but with data_dir, although i would like to discuss the problem you are trying to solve as that might not be necessary

**Comment by idky137** [comment]
I agree there is probably a better approach to this, the problem is that ReadStateService requires access to Zebra's data dir, this is easy when we are loading from cached chain data but currently when we are not loading from cache the data dir is hidden to client code. 

For us to be able to test the ReadStateService we will need access to this data dir, whether it is given as an input or returned by the spawn method.

This is complicated by the fact Zebra's ReadStateService takes a PathBuf, so we cannot directly pass a TempDir.

**Comment by Oscar-Pepper** [comment]
> I agree there is probably a better approach to this, the problem is that ReadStateService requires access to Zebra's data dir, this is easy when we are loading from cached chain data but currently when we are not loading from cache the data dir is hidden to client code.
> 
> For us to be able to test the ReadStateService we will need access to this data dir, whether it is given as an input or returned by the spawn method.
> 
> This is complicated by the fact Zebra's ReadStateService takes a PathBuf, so we cannot directly pass a TempDir.
> 
> EDIT: Added context, Zaino is currently using this branch of zcash-local-net so it can test the ReadStateService.

sorry im still not quite following the issue, so the `data_dir` is a pub trait method that you have access to right? so could you not call `zebrad.data_dir().path().to_path_buf()` to get the pathbuf to zebras datadir and pass to the ReadstateService?

this is an exmaple of where we get the PathBuf for the TempDir here:
https://github.com/zingolabs/zcash-local-net/pull/25/files#diff-bb93d438014a3dabda263f8e12d6d6db09cf79f2313c77271fca77be9dba8d04L160

**Comment by idky137** [comment]
Ah I see sorry yes that is better. i will make changes in zaino.

**Pull request closed without merging**
